/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/dropdownTest`; params?: Router.UnknownInputParams; } | { pathname: `/footer`; params?: Router.UnknownInputParams; } | { pathname: `/friends`; params?: Router.UnknownInputParams; } | { pathname: `/Header`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/matchmaking`; params?: Router.UnknownInputParams; } | { pathname: `/referee`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/tournament`; params?: Router.UnknownInputParams; } | { pathname: `/userProfile`; params?: Router.UnknownInputParams; } | { pathname: `/userProfileSettings`; params?: Router.UnknownInputParams; } | { pathname: `/WeekAvailability`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/database`; params?: Router.UnknownOutputParams; } | { pathname: `/dropdownTest`; params?: Router.UnknownOutputParams; } | { pathname: `/footer`; params?: Router.UnknownOutputParams; } | { pathname: `/friends`; params?: Router.UnknownOutputParams; } | { pathname: `/Header`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/matchmaking`; params?: Router.UnknownOutputParams; } | { pathname: `/referee`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/tournament`; params?: Router.UnknownOutputParams; } | { pathname: `/userProfile`; params?: Router.UnknownOutputParams; } | { pathname: `/userProfileSettings`; params?: Router.UnknownOutputParams; } | { pathname: `/WeekAvailability`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/database${`?${string}` | `#${string}` | ''}` | `/dropdownTest${`?${string}` | `#${string}` | ''}` | `/footer${`?${string}` | `#${string}` | ''}` | `/friends${`?${string}` | `#${string}` | ''}` | `/Header${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/matchmaking${`?${string}` | `#${string}` | ''}` | `/referee${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/tournament${`?${string}` | `#${string}` | ''}` | `/userProfile${`?${string}` | `#${string}` | ''}` | `/userProfileSettings${`?${string}` | `#${string}` | ''}` | `/WeekAvailability${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/database`; params?: Router.UnknownInputParams; } | { pathname: `/dropdownTest`; params?: Router.UnknownInputParams; } | { pathname: `/footer`; params?: Router.UnknownInputParams; } | { pathname: `/friends`; params?: Router.UnknownInputParams; } | { pathname: `/Header`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/matchmaking`; params?: Router.UnknownInputParams; } | { pathname: `/referee`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/tournament`; params?: Router.UnknownInputParams; } | { pathname: `/userProfile`; params?: Router.UnknownInputParams; } | { pathname: `/userProfileSettings`; params?: Router.UnknownInputParams; } | { pathname: `/WeekAvailability`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
